{{toYaml cfg.backend}}
state-dir: "{{ pkg.svc_data_path }}"
cache-dir: "{{ pkg.svc_var_path }}"

##
# agent configuration
##

{{#if cfg.use_dns }}agent-host: "{{sys.hostname}}"{{else}}agent-host: "{{sys.ip}}"{{/if}}
agent-port: {{cfg.agent-port}}

##
# api configuration
##

api-listen-address: "[::]:{{cfg.api-port}}"
{{#if cfg.use_dns }}api-url: "http://{{sys.hostname}}:{{cfg.api-port}}"{{else}}api-url: "http://{{sys.ip}}:{{cfg.api-port}}"{{/if}}
